version: "3.3"
services:
  server:
    container_name: http-server
    restart: always
    image: akrahl/nginx-docker:http1
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - /var/www/html:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/log:/var/log
    environment:
      - DOMAINNAME=
    privileged: true
  proxy:
    container_name: http-proxy
    restart: always
    image: akrahl/nginx-docker:http1proxy
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/log:/var/log
    environment:
      - DOMAINNAME=
    privileged: true
