version: "3.3"
services:
  server:
    container_name: http-server
    restart: always
    image: akrahl/nginx-docker:http3
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - /var/www/html:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - DOMIANNAME=
    privileged: true
